import type { PlayersData } from "../types/data";

// export const players: PlayersData  = [
//   {
//     id: 1,
//     name: 'Frankito',
//     team: 'Red Devils FC',
//     photo: '/frankito.jpg',
//   },
//   {
//     id: 2,
//     name: 'Kanuto',
//     team: 'Red Devils FC',
//     photo: '',
//   },
//   {
//     id: 3,
//     name: 'Josue',
//     team: 'Red Devils FC',
//     photo: '',
//   },
//   {
//     id: 4,
//     name: 'Wachi',
//     team: 'Red Devils FC',
//     photo: '',
//   },
//   {
//     id: 5,
//     name: 'Wincho',
//     team: 'Red Devils FC',
//     photo: '',
//   },
//   {
//     id: 6,
//     name: 'Renzo',
//     team: 'Red Devils FC',
//     photo: '',
//   },
//     {
//     id: 7,
//     name: 'Garfield',
//     team: 'Red Devils FC',
//     photo: '',
//   },
//   {
//     id: 8,
//     name: 'Omar',
//     team: 'Realcoholicos FC',
//     photo: '',
//   },
//   {
//     id: 9,
//     name: 'Pedro',
//     team: 'Realcoholicos FC',
//     photo: '',
//   },
//   {
//     id: 10,
//     name: 'Heraldo',
//     team: 'Realcoholicos FC',
//     photo: '',
//   },
//   {
//     id: 11,
//     name: 'Lucho',
//     team: 'Realcoholicos FC',
//     photo: '',
//   },
//   {
//     id: 12,
//     name: 'Russo',
//     team: 'Realcoholicos FC',
//     photo: '/russo.jpg',
//   },
//   {
//     id: 13,
//     name: 'Favio',
//     team: 'Realcoholicos FC',
//     photo: '',
//   },
//   {
//     id: 14,
//     name: 'Sebastian',
//     team: 'Realcoholicos FC',
//     photo: '',
//   },
//       {
//     id: 15,
//     name: 'Jozua',
//     team: 'FC Real Polaco',
//     photo: '/jozua.jpg',
//   },
//   {
//     id: 16,
//     name: 'Rodrigo',
//     team: 'FC Real Polaco',
//     photo: '',
//   },
//   {
//     id: 17,
//     name: 'Charly',
//     team: 'FC Real Polaco',
//     photo: '',
//   },
//   {
//     id: 18,
//     name: 'Edder',
//     team: 'FC Real Polaco',
//     photo: '',
//   },
//   {
//     id: 19,
//     name: 'Pitbull',
//     team: 'FC Real Polaco',
//     photo: '',
//   },
//   {
//     id: 20,
//     name: 'Yair',
//     team: 'FC Real Polaco',
//     photo: '',
//   },
//   {
//     id: 21,
//     name: 'Liam',
//     team: 'FC Real Polaco',
//     photo: '',
//   },
// ]

export const players: PlayersData  = [
  {
    id: 1,
    name: 'Frankito',
    team: 'Red Devils FC',
    photo: '/frankito.jpg',
  },
  {
    id: 2,
    name: 'Kanuto',
    team: 'Red Devils FC',
    photo: '',
  },
  {
    id: 3,
    name: 'Josue',
    team: 'Red Devils FC',
    photo: '/josue.png',
  },
  {
    id: 4,
    name: 'Wachi',
    team: 'Red Devils FC',
    photo: '',
  },
  {
    id: 5,
    name: 'Favio',
    team: 'Red Devils FC',
    photo: '',
  },
  {
    id: 6,
    name: 'Pedrito',
    team: 'Red Devils FC',
    photo: '',
  },
    {
    id: 7,
    name: 'Lucho',
    team: 'Red Devils FC',
    photo: '',
  },
  {
    id: 8,
    name: 'Daniel',
    team: 'Realcoholicos FC',
    photo: '/daniel.png',
  },
  {
    id: 9,
    name: 'Jose Daniel',
    team: 'Realcoholicos FC',
    photo: '',
  },
  {
    id: 10,
    name: 'Heraldo',
    team: 'Realcoholicos FC',
    photo: '',
  },
  {
    id: 11,
    name: 'Joel',
    team: 'Realcoholicos FC',
    photo: '',
  },
  {
    id: 12,
    name: 'Russo',
    team: 'Realcoholicos FC',
    photo: '/russo.jpg',
  },
  {
    id: 13,
    name: 'Wincho',
    team: 'Realcoholicos FC',
    photo: '',
  },
  {
    id: 14,
    name: 'Sebastian',
    team: 'Realcoholicos FC',
    photo: '',
  },
      {
    id: 15,
    name: 'Jozua',
    team: 'FC Real Polaco',
    photo: '/jozua.jpg',
  },
  {
    id: 16,
    name: 'Rodrigo',
    team: 'FC Real Polaco',
    photo: '',
  },
  {
    id: 17,
    name: 'Charly',
    team: 'FC Real Polaco',
    photo: '/charly.jpg',
  },
  {
    id: 18,
    name: 'Omar',
    team: 'FC Real Polaco',
    photo: '/omar.jpg',
  },
  {
    id: 19,
    name: 'Pitbull',
    team: 'FC Real Polaco',
    photo: '',
  },
  {
    id: 20,
    name: 'Yair',
    team: 'FC Real Polaco',
    photo: '',
  },
  {
    id: 21,
    name: 'Liam',
    team: 'FC Real Polaco',
    photo: '',
  },
  {
    id: 22,
    name: 'Mathias',
    team: 'FC Real Polaco',
    photo: '',
  },
]